# Generated by Django 5.1.1 on 2024-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, null=True)),
                ('image', models.FileField(default=None, upload_to='slider')),
                ('image_order', models.IntegerField()),
                ('enabled', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name_plural': 'sliders',
                'db_table': 'sliders',
            },
        ),
    ]
