# Generated by Django 5.1.1 on 2024-09-17 02:43

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('code', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('size', models.CharField(max_length=300, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('image', models.FileField(default=None, upload_to='slider')),
                ('date_of_upload', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
    ]
